pretrained_model_name_or_path: stable-diffusion-v1-5/stable-diffusion-inpainting # This is a mirror image of ruwnayml/stable-diffusion-v1-5
dataroot_path: DressCode
output_dir: outputs
seed: 42
order: paired
inference_grid: dresscode_{}_grid
inference_one: dresscode_{}_one
test_batch_size: 1
dataloader_num_workers: 16
mixed_precision: fp16
ip_scale: 1.0
size: [512, 384]
uncond_prob: 0.0
concat_dim: 3
resume_state: checkpoints/dresscode_checkpoint-1451399-step
guidance_scale: 1.5
num_inference_steps: 50