pretrained_model_name_or_path: stable-diffusion-v1-5/stable-diffusion-inpainting # This is a mirror image of ruwnayml/stable-diffusion-v1-5
pretrained_ip_adapter_path: ip-adapter_sd15.bin
dataroot_path: vitonhd  
seed: 42
output_dir: outputs

learning_rate: 1.0e-05
weight_decay: 1.0e-2
max_train_steps: 512000 # 175 epoch
train_batch_size: 4
dataloader_num_workers: 24
mixed_precision: fp16

ip_scale: 1.0
size: [512, 384]
uncond_prob: 0.2
concat_dim: 3
log_info_every_n_steps: 10
warm_up_steps: 500
resume_state: ""

wandb_project: None # None or Ti-MGD


